[roll third_party/pigweed] pw_docgen: sphinxcontrib-mermaid workaround:
Version >=4.0.0 of Sphinx removes some APIs, one of which is used by
sphinxcontrib-mermaid. Error:

Running Sphinx v4.0.0
Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name
'ENOENT' from 'sphinx.util.osutil'

Failed roll:
https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/44223

This workaround can be removed after
https://github.com/mgaitan/sphinxcontrib-mermaid/pull/71 is merged.

No-Docs-Update-Reason: Sphinx 4.0 workaround.
Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/44320

third_party/pigweed Rolled-Commits: 778529737faa78c..56f4a2cdc97d341
Roller-URL: https://ci.chromium.org/b/8847587023946615184
Cq-Cl-Tag: roller-builder:pigweed-experimental-roller
Cq-Cl-Tag: roller-bid:8847587023946615184
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I87c5eaeacda794e3418c13c7898429b01dce6070
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/experimental/+/44400
Reviewed-by: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>