[roll third_party/pigweed] pw_rpc: Fix mimxrt595_evk target
A change(1) was merged that broke the mimxrt595_evk target. Adding
A pw_rpc_CONFIG GN variable to fix this target. Fixes the following
build error:

```
../pw_rpc/endpoint.cc:41:15: error: static assertion failed: PW_RPC_YIELD_MODE
   is PW_RPC_YIELD_MODE_SLEEP (pw::this_thread::sleep_for()), but no backend
   is set for pw_thread:sleep. Set a pw_thread:sleep backend or use a
   different PW_RPC_YIELD_MODE setting.
   41 | static_assert(false,
      |               ^~~~~
../pw_rpc/endpoint.cc: In function 'void pw::rpc::internal::YieldRpcLock()':
../pw_rpc/endpoint.cc:85:20: error: 'chrono' does not name a type
   85 |   static constexpr chrono::SystemClock::duration kSleepDuration =
      |                    ^~~~~~
../pw_rpc/endpoint.cc:87:3: error: 'this_thread' has not been declared
   87 |   this_thread::sleep_for(kSleepDuration);
      |   ^~~~~~~~~~~
../pw_rpc/endpoint.cc:87:26: error: 'kSleepDuration' was not declared in this scope
   87 |   this_thread::sleep_for(kSleepDuration);
      |                          ^~~~~~~~~~~~~~
[46/388] c++ mimxrt595_evk_debug/obj/pw_rpc/nanopb/codegen_test.lib.codegen_test.cc.o
```

(1) Breaking Change-Id: I94517d66e04b51b95a911adac560426ee3683388

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/128910

https://pigweed.googlesource.com/pigweed/pigweed
third_party/pigweed Rolled-Commits: bdb5dc796799f66..e996d631809d541
Roller-URL: https://ci.chromium.org/b/8789091828602882961
GitWatcher: ignore
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I0d11cd32787066e4f7fa6381a1dd8a5b86954feb
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/experimental/+/129211
Bot-Commit: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>