[roll third_party/pigweed] pw_console: Missing default_factory for dataclasses
Fixes the Python 3.11 error:
ValueError: mutable default <class 'collections.deque'> for field
history is not allowed: use default_factory.

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/135481

https://pigweed.googlesource.com/pigweed/pigweed
third_party/pigweed Rolled-Commits: f4dd9366fb797dd..7e67d0fb4d1e033
Roller-URL: https://ci.chromium.org/b/8785728081301338577
GitWatcher: ignore
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: Ifbb5e13dc5ff943c81cc9028cb9ed85be1df5fed
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/experimental/+/135552
Bot-Commit: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>