[roll third_party/pigweed] pw_cli: Fix logging msec format
Python 3.8 and lower does not check if default_msec_format is set.
Fixes these Logging errors:

```
TypeError: not all arguments converted during string formatting
```

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/130472

https://pigweed.googlesource.com/pigweed/pigweed
third_party/pigweed Rolled-Commits: 3e6fc972112cd0b..6ed549f33032e74
Roller-URL: https://ci.chromium.org/b/8788352780244625585
GitWatcher: ignore
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: Idfe6e45f24a380da8cefeac30f3aefecbead9e6b
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/experimental/+/130519
Bot-Commit: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>