[roll third_party/pigweed] Revert "roll: rbe-client"
This reverts commit 92b422f173fad5d7d09eed5bb2d91f28911e1aa8.

Reason for revert: multiple instances with this re_client_version

$ cipd describe -version re_client_version:0.42.0.eaa4fb6 infra/rbe/client/windows-amd64
Error: ambiguity when resolving the tag, more than one instance has it.

Original change's description:
> roll: rbe-client
>
> From: re_client_version:0.41.4.3f0d8bb
> To: re_client_version:0.42.0.eaa4fb6
>
> CQ-Do-Not-Cancel-Tryjobs: true
> Roller-URL: https://ci.chromium.org/b/8834453533194835521
> Cq-Cl-Tag: roller-builder:rbe-client-roller
> Cq-Cl-Tag: roller-bid:8834453533194835521
> CQ-Do-Not-Cancel-Tryjobs: true
> Change-Id: I24b76a17bf4481cd64fee2c855e61ed43e2c54f8
> Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/63460
> Bot-Commit: Pigweed Roller <pigweed-roller@pigweed.google.com.iam.gserviceaccount.com>
> Commit-Queue: Pigweed Roller <pigweed-roller@pigweed.google.com.iam.gserviceaccount.com>

# Not skipping CQ checks because original CL landed > 1 day ago.

Original-Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/63900

https://pigweed.googlesource.com/pigweed/pigweed
third_party/pigweed Rolled-Commits: bee7e33bfa3b9b7..0dd5a8b315cb8e6
Roller-URL: https://ci.chromium.org/b/8834197236224508033
Cq-Cl-Tag: roller-builder:pigweed-experimental-roller
Cq-Cl-Tag: roller-bid:8834197236224508033
CQ-Do-Not-Cancel-Tryjobs: true
Change-Id: I7638a7e6de05922f0c5a028141b0c04ea9cb8859
Reviewed-on: https://pigweed-review.googlesource.com/c/pigweed/experimental/+/63921
Bot-Commit: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>
Commit-Queue: Pigweed Integration Roller <pigweed-integration-roller@pigweed.google.com.iam.gserviceaccount.com>